const { GoogleSpreadsheet } = require('google-spreadsheet')

const {
  GOOGLE_OTTOLISTED_SHEET_ID,
  GOOGLE_OTTOLISTED_PRIVATE_KEY,
  GOOGLE_OTTOLISTED_CLIENT_EMAIL,
} = process.env

const newSheetsClient = async ({
  sheetId = GOOGLE_OTTOLISTED_SHEET_ID,
  email = GOOGLE_OTTOLISTED_CLIENT_EMAIL,
  priKey = GOOGLE_OTTOLISTED_PRIVATE_KEY,
} = {}) => {
  const doc = new GoogleSpreadsheet(sheetId)

  // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: email,
    private_key: priKey,
  })

  await doc.loadInfo() // loads document properties and worksheets
  return doc
}

module.exports = {
  newSheetsClient,
}
